!classDefinition: #Pepe category: #'Ejercicio 1'!
DenotativeObject subclass: #Pepe
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Pepe class' category: #'Ejercicio 1'!
Pepe class
	instanceVariableNames: ''!

!Pepe class methodsFor: 'as yet unclassified' stamp: 'HAW 13/Aug/2026, 3:17:54 pm (UTC)'!
!methodProperties: {}!
hola
	^'chau'! !
